# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5146d6bddd1844bbe0bcbf72f74510f4403ef2379f390f8491041db48181862fb9dafaba4b3cb12d8591267be714aadb69fa867e05816fafa2e791e46e334755

test:
  secret_key_base: b8f7cb19822f33be79c789c289c2ddcf649e79bf54383096231703e62208c0bacf3e3b25e59f2a99d6eb109f5de55c4c00a654784c2def28b0caad21ace59b2a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
